configserver:
    name: Docker JHipster Registry
    status: Connected to the JHipster Registry running in Docker

spring:
    application:
        name: jhipster-registry
	cloud:
	    config:
		    fail-fast: true

eureka:
    instance:
	    appname: registry
    client:
        service-url:
            defaultZone: http://admin:admin@registry:8761/eureka/
	    fetch-registry: true
		register-with-eureka: true

jhipster:
    security:
        authentication:
            jwt:
                secret: 6c3083a1ba0dbdc53cb9b22ec17013c745a401fe6c3083a1ba0dbdc53cb9b22ec17013c745a401fe
