configserver:
    name: JHipster Registry Config Server
    status: Connected to the JHipster Registry Config Server

spring:
    cloud:
        config:
             fail-fast: true
    datasource:
        url: jdbc:postgresql://postgres:5432/postgres
        username: dbadmin
        password: Xq2k1Y7VRrsuzM5T

eureka:
    instance:
    client:
        serviceUrl:
             defaultZone: http://admin:admin@registry1:8761/eureka/,http://admin:admin@registry2:8761/eureka/

liquibase:
     contexts: dev,testdata
     
uaa:
     web-client-configuration:
              secret: ks6Q7ODOOEmMcXCIhGVn

jhipster:
     security:
        authentication:
            jwt:
                secret: 6c3083a1ba0dbdc53cb9b22ec17013c745a401fe6c3083a1ba0dbdc53cb9b22ec17013c745a401fe  

application:  
    security:
        unycom-authorization:
            client-secret: unycom!123
        argos-authorization:
            client-secret: ipss!123
        ipss-authorization:
            client-secret: argos!123
        ipfolio-authorization:
            client-secret: ipfolio!123
        patorg-authorization:
            client-secret: patorg!123
        genese-authorization:
            client-secret: genese!123
        greip-authorization:
            client-secret: greip!123
