configserver:
    name: JHipster Registry Config Server
    status: Connected to the JHipster Registry Config Server

spring:
    cloud:
        config:
             fail-fast: true
    datasource:
        url: jdbc:postgresql://postgres:5432/postgres
        username: dbadmin
        password: Xq2k1Y7VRrsuzM5T

eureka:
    client:
        serviceUrl:
             defaultZone: http://admin:admin@registry1:8761/eureka/,http://admin:admin@registry2:8761/eureka/

liquibase:
     contexts: dev,testdata
     
uaa:
     web-client-configuration:
              secret: ks6Q7ODOOEmMcXCIhGVn

application:  
    security:
        unycom-authorization:
            client-secret: vlad123
        argos-authorization:
            client-secret: vlad123
        ipss-authorization:
            client-secret: vlad123
        ipfolio-authorization:
            client-secret: vlad123
        patorg-authorization:
            client-secret: vlad123
        genese-authorization:
            client-secret: vlad123
        greip-authorization:
            client-secret: vlad123
